require('joecrowley.lazy')
require('joecrowley.filetypes')
require('joecrowley.keymap')
require('joecrowley.themes')
require('joecrowley.lsp')
require('joecrowley.oil')
require('joecrowley.auto-save')
require('joecrowley.cmp')
require('joecrowley.lualine')
require('joecrowley.treesitter')
require('joecrowley.telescope')
require('joecrowley.dap')

